// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSr2mKtrYkHpGkDO3JkJ0BnWGEywo6cw',
    appId: '1:700552874815:web:3593efb1a97c141aa8218a',
    messagingSenderId: '700552874815',
    projectId: 'flutter-firebase-app-4e186',
    authDomain: 'flutter-firebase-app-4e186.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-4e186.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wn4Dg1qFjfdDyVXG8l3CpcCFPMF2V6I',
    appId: '1:700552874815:android:6b87c5c942237d4da8218a',
    messagingSenderId: '700552874815',
    projectId: 'flutter-firebase-app-4e186',
    storageBucket: 'flutter-firebase-app-4e186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATJcF6omjPHbbBBz0W0xxaq6C-3XbM0xg',
    appId: '1:700552874815:ios:d23000a0185e4c90a8218a',
    messagingSenderId: '700552874815',
    projectId: 'flutter-firebase-app-4e186',
    storageBucket: 'flutter-firebase-app-4e186.appspot.com',
    iosClientId: '700552874815-093r6f3mp82o0ksm19e6sln7jnfmflq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATJcF6omjPHbbBBz0W0xxaq6C-3XbM0xg',
    appId: '1:700552874815:ios:d23000a0185e4c90a8218a',
    messagingSenderId: '700552874815',
    projectId: 'flutter-firebase-app-4e186',
    storageBucket: 'flutter-firebase-app-4e186.appspot.com',
    iosClientId: '700552874815-093r6f3mp82o0ksm19e6sln7jnfmflq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
